#!/bin/bash

#############
# FUNCTIONS #
#############

function installation_manager() {
    echo "package manager found: $1!"
    # add user input for "y/n installation"
    if [[ $1 = "apt" ]]; then
        sudo apt update && sudo apt upgrade && sudo apt install $(cat ./lists/apt.list)
    elif [[ $1 = "dnf" ]]; then
        sudo dnf upgrade && sudo dnf install $(cat ./lists/dnf.list)
    elif [[ $1 = "pacman" ]]; then
        sudo pacman -Syyu && sudo pacman -S $(cat ./lists/pacman.list)
    elif [[ $1 = "zypper" ]]; then
        sudo zypper ref && sudo zypper update && sudo zypper install $(cat ./lists/zypper.list)
    elif [[ $1 = "emerge" ]]; then
        sudo emerge -avDuN world && sudo emerge -av $(cat ./lists/emerge.list)
    elif [[ $1 = "flatpak" ]]; then
        sudo flatpak update && sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && sudo flatpak install $(cat ./lists/flatpak.list)
    fi
}

########
# CODE #
########

# Get package manager name
package_managers=("apta" "dnf" "pacman" "zypper" "emerge")
has_found=0
package_manager_found=""
for element in "${package_managers[@]}"; do
    which "$element" > /dev/null
    if [[ $? -eq 0 ]]; then
        has_found=1
        package_manager_found=$element
    fi
done

# .
if [[ has_found -eq 1 ]]; then
    installation_manager $package_manager_found
else
    echo "I couldn't find any known package manager..."
    which "flatpak" > /dev/null
    if [[ $? -eq 0 ]]; then
        echo "A flatpak setup has been found... lucky you there's an available flatpak installation for the epitech dump!"
        # add user input for "y/n installation"
        installation_manager "flatpak"
    else
        echo "No flatpak installation couldn't be found.. Go check if your distro is eligible for flatpak: https://flatpak.org/setup/"
        printf "2 cases:\n%s\n%s\n" "- If you can see your distro in the list: congrats, you're saved! Go setup flatpak (on the same link) and come back to install the packages." "- If you can't see your distro in the list, I'm sorry because you won't be able to install the epitech dump on your current system... unless you install every package from source."
    fi
fi
